spring:
  application:
    name: API-Gateway
  cloud:
    gateway:
      routes:
      - id: Owner
        uri: http://localhost:8081/
        predicates:
        - Path=/owner/**
      - id: Manager
        uri: http://localhost:8082/
        predicates:
        - Path=/manager/**
      - id: Receptionist
        uri: http://localhost:8083/
        predicates:
        - Path=/reception/**
          

server:
  port: 8080


